apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: saute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/cdot65/saute-backend:0.0.1
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
          limits:
            cpu: 5000m
            memory: 4000Mi
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        volumeMounts:
        - name: backend-data
          mountPath: /code
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      volumes:
      - name: backend-data
        persistentVolumeClaim:
          claimName: backend-pvc
