apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: saute
data:
  DJANGO_ALLOWED_HOSTS: '["localhost", "127.0.0.1", "*"]'
  DJANGO_DEBUG: "False"
  POSTGRES_DB: "postgres"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  OPENAI_TEMPERATURE: "0.6"
  OPENAI_MAX_TOKENS: "4096"
