apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: saute
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  selector:
    matchLabels:
      name: db-pv
