apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: saute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.5-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
          limits:
            cpu: 5000m
            memory: 4000Mi
