apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: saute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: ghcr.io/cdot65/saute-worker:0.0.1
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
          limits:
            cpu: 5000m
            memory: 4000Mi
        command: ["celery", "-A", "django_project", "worker", "-l", "info"]
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        volumeMounts:
        - name: backend-data
          mountPath: /code
      volumes:
      - name: backend-data
        persistentVolumeClaim:
          claimName: backend-pvc
