apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pan-os-telemetry
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.global.scrape_interval }}
      scrape_timeout: {{ .Values.prometheus.config.global.scrape_timeout }}
      evaluation_interval: {{ .Values.prometheus.config.global.evaluation_interval }}
    scrape_configs:
      {{- range .Values.prometheus.config.scrape_configs }}
      - job_name: {{ .job_name }}
        metrics_path: {{ .metrics_path }}
        static_configs:
          - targets:
              {{- range .static_configs }}
              {{- range .targets }}
              - {{ . }}
              {{- end }}
              {{- end }}
        relabel_configs:
          {{- range .relabel_configs }}
          - source_labels: [{{ .source_labels | join "," }}]
            target_label: {{ .target_label }}
            {{- if .replacement }}
            replacement: {{ .replacement }}
            {{- end }}
          {{- end }}
      {{- end }}