apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: pan-os-telemetry
  labels:
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      {{- if eq .Values.grafana.service.type "NodePort" }}
      nodePort: {{ .Values.grafana.service.nodePort }}
      {{- end }}
  selector:
    app: grafana
