---
vsys:
  name: "vsys1"
  zones:
    - name: "DMZ"
      iface: "ethernet1/2"
      mode: "layer3"

    - name: "WAN"
      iface: "ethernet1/1"
      mode: "layer3"

  addresses:
    - name: "WAN_IPv4"
      ip_mask: "74.51.192.2/30"
      description: "WAN interface BGP session"

    - name: "DMZ_IPv4"
      ip_mask: "192.168.100.1/24"

    - name: "hdq-ifw-01_WAN"
      ip_mask: "74.51.192.1"
