---
# 01-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-edl-config
  namespace: dev-edl
data:
  POSTGRES_DB: "edl_db"
  POSTGRES_PORT: "5432"
  FRONTEND_URL: "https://dev.edl.cdot.io"
