- name: Create static default route
  panos_static_route:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "panofficehours"
      password: "paloalto1!"
    name: "{{ item.name }}"
    destination: "{{ item.destination }}"
    nexthop: "{{ item.nexthop }}"
    virtual_router: "{{ item.vr }}"
  loop: "{{ static_routes }}"
