{
 "title": "PanOS (REST-XML)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host Name",
    "query": {
     "query": "label_values(panos_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "panos_up{instance=~\"$host\", job=\"panos_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "panos_data_plane_resource_util_cpu_load_average{instance=\"$host\", job=\"panos_exporter\"}",
     "legendFormat": "{{ coreid }}"
    }
   ]
  },
  {
   "title": "HW TX Data Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(panos_interface_counter_hw_tx_bytes{instance=\"$host\", job=\"panos_exporter\"}[30s])/30",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "HW Rx Data Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(panos_interface_counter_hw_rx_bytes{instance=\"$host\", job=\"panos_exporter\"}[30s])/30",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}