# Generated by Django 5.0.8 on 2024-08-17 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='connection_hostname',
            field=models.CharField(blank=True, help_text='Hostname or FQDN for SSH connection', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='connection_ipv4',
            field=models.GenericIPAddressField(blank=True, help_text='IPv4 address for SSH connection', null=True, protocol='IPv4', validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='connection_ipv6',
            field=models.GenericIPAddressField(blank=True, help_text='IPv6 address for SSH connection', null=True, protocol='IPv6', validators=[django.core.validators.validate_ipv6_address]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(help_text='Device hostname or FQDN', max_length=255),
        ),
    ]
