auth:
  panorama:
    username: "my-panorama-username-was-here"
    password: "my-panorama-password-was-here"
  firewall:
    username: "my-firewall-username-was-here"
    password: "my-firewall-password-was-here"