---
# secrets.yaml

oauth:
  token_url: "https://auth.apps.paloaltonetworks.com/oauth2/access_token"
  source:
    client_id: "this-is-a-placeholder"
    client_secret: "this-is-a-placeholder"
    tsg: "this-is-a-placeholder"
  destination:
    client_id: "this-is-a-placeholder"
    client_secret: "this-is-a-placeholder"
    tsg: "this-is-a-placeholder"
