crypto_profiles:
  - name: "remote-office-crypto-profile"
    dh_group: ["group2"]
    authentication: ["sha1"]
    encryption: ["aes-128-cbc"]
    lifetime: "28800"

  - name: "cloud-crypto-profile"
    dh_group: ["group2"]
    authentication: ["sha256"]
    encryption: ["aes-256-cbc"]
    lifetime: "28800"

ipsec_profiles:
  - name: "remote-branch-ipsec-profile"
    authentication: ["sha1"]
    encryption: ["aes-128-cbc"]
    lifetime: "3600"
