# Generated by Django 5.0.8 on 2024-08-23 12:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('PAN-OS NGFW', 'PAN-OS NGFW'), ('Panorama', 'Panorama')], max_length=20)),
                ('device_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hostname', models.CharField(help_text='Device hostname or FQDN', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('connection_hostname', models.CharField(blank=True, help_text='Hostname or FQDN for SSH connection', max_length=255, null=True)),
                ('connection_ipv4', models.GenericIPAddressField(blank=True, help_text='IPv4 address for SSH connection', null=True, protocol='IPv4', validators=[django.core.validators.validate_ipv4_address])),
                ('connection_ipv6', models.GenericIPAddressField(blank=True, help_text='IPv6 address for SSH connection', null=True, protocol='IPv6', validators=[django.core.validators.validate_ipv6_address])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
