# config/objects/external_dynamic_lists.yaml
panos_config:
  device_groups:
    Magnolia:
      objects:
        external_dynamic_lists:
          - name: "Malware_IP_List"
            edl_type: "ip"
            description: "Known malware IP addresses"
            source: "https://lists.example.com/malware-ips.txt"
            repeat: "hourly"

          - name: "Phishing_Domains"
            edl_type: "domain"
            description: "Recent phishing domains"
            source: "https://lists.example.com/phishing-domains.txt"
            repeat: "daily"
            repeat_at: "02:00"

          - name: "Botnet_C2_Servers"
            edl_type: "ip"
            description: "Botnet command and control servers"
            source: "https://lists.example.com/botnet-c2.txt"
            repeat: "hourly"

          - name: "Tor_Exit_Nodes"
            edl_type: "ip"
            description: "Tor exit node IP addresses"
            source: "https://lists.example.com/tor-exits.txt"
            repeat: "daily"
            repeat_at: "00:00"

          - name: "Cryptocurrency_Mining_Pools"
            edl_type: "domain"
            description: "Known cryptocurrency mining pool domains"
            source: "https://lists.example.com/crypto-mining-pools.txt"
            repeat: "daily"
            repeat_at: "01:00"

          - name: "Spam_IP_List"
            edl_type: "ip"
            description: "Known spam source IP addresses"
            source: "https://lists.example.com/spam-ips.txt"
            repeat: "hourly"

          - name: "Malicious_URLs"
            edl_type: "url"
            description: "Recently identified malicious URLs"
            source: "https://lists.example.com/malicious-urls.txt"
            repeat: "hourly"

          - name: "DGA_Domains"
            edl_type: "domain"
            description: "Domain Generation Algorithm domains"
            source: "https://lists.example.com/dga-domains.txt"
            repeat: "daily"
            repeat_at: "03:00"

          - name: "Ransomware_IPs"
            edl_type: "ip"
            description: "IP addresses associated with ransomware"
            source: "https://lists.example.com/ransomware-ips.txt"
            repeat: "hourly"

          - name: "Malvertising_Domains"
            edl_type: "domain"
            description: "Domains associated with malvertising"
            source: "https://lists.example.com/malvertising-domains.txt"
            repeat: "daily"
            repeat_at: "04:00"

          - name: "APT_IP_List"
            edl_type: "ip"
            description: "IP addresses associated with APT groups"
            source: "https://lists.example.com/apt-ips.txt"
            repeat: "daily"
            repeat_at: "05:00"

          - name: "Compromised_Websites"
            edl_type: "url"
            description: "Recently compromised legitimate websites"
            source: "https://lists.example.com/compromised-sites.txt"
            repeat: "hourly"

          - name: "DDoS_Source_IPs"
            edl_type: "ip"
            description: "Source IP addresses of recent DDoS attacks"
            source: "https://lists.example.com/ddos-source-ips.txt"
            repeat: "hourly"

          - name: "Typosquatting_Domains"
            edl_type: "domain"
            description: "Known typosquatting domains"
            source: "https://lists.example.com/typosquatting-domains.txt"
            repeat: "daily"
            repeat_at: "06:00"

          - name: "Exploit_Kit_URLs"
            edl_type: "url"
            description: "URLs associated with exploit kits"
            source: "https://lists.example.com/exploit-kit-urls.txt"
            repeat: "hourly"

          - name: "Anonymizer_Proxies"
            edl_type: "ip"
            description: "IP addresses of anonymizer proxies"
            source: "https://lists.example.com/anonymizer-proxies.txt"
            repeat: "daily"
            repeat_at: "07:00"

          - name: "Malicious_JS_Hosts"
            edl_type: "domain"
            description: "Hosts serving malicious JavaScript"
            source: "https://lists.example.com/malicious-js-hosts.txt"
            repeat: "hourly"

          - name: "Phishing_Kit_URLs"
            edl_type: "url"
            description: "URLs hosting phishing kits"
            source: "https://lists.example.com/phishing-kit-urls.txt"
            repeat: "hourly"

          - name: "Cryptojacking_Domains"
            edl_type: "domain"
            description: "Domains associated with cryptojacking"
            source: "https://lists.example.com/cryptojacking-domains.txt"
            repeat: "daily"
            repeat_at: "08:00"

          - name: "Malware_Distribution_Points"
            edl_type: "ip"
            description: "IP addresses of malware distribution points"
            source: "https://lists.example.com/malware-distribution-ips.txt"
            repeat: "hourly"
