services:
  docs:
    image: cdss_certificate_remediation_local_docs
    container_name: cdss_certificate_remediation_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_project:/app/django_project:z
    ports:
      - '9000:9000'
    command: /start-docs
