#!/bin/bash
# compose/local/django/celery/beat/start

set -o errexit
set -o nounset


rm -f './celerybeat.pid'
exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app beat -l INFO'
