[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"

[api]
insecure = true
dashboard = true

[providers.docker]
exposedByDefault = false
network = "cdss_certificate_remediation_default"

[certificatesResolvers.myresolver.acme]
email = "your-email@example.com"
storage = "acme.json"
[certificatesResolvers.myresolver.acme.httpChallenge]
entryPoint = "web"

[tls.options]
[tls.options.default]
minVersion = "TLSv1.2"

[[tls.certificates]]
certFile = "/etc/traefik/certs/traefik-local.crt"
keyFile = "/etc/traefik/certs/traefik-local.key"

[http.routers.django]
rule = "Host(`localhost`) || Host(`127.0.0.1`) || Host(`0.0.0.0`) || Host(`django.localhost`)"
entrypoints = ["websecure"]
service = "django"
[http.routers.django.tls]
certresolver = "myresolver"

[http.services.django.loadBalancer]
[[http.services.django.loadBalancer.servers]]
url = "http://django:8000"

